/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetobd;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import projetobd.Model.Aluno_RN;
import projetobd.Model.Aluno_VO;

/**
 *
 * @author JonathanRLima
 */
public class FAluno extends javax.swing.JFrame {

    /**
     * Creates new form FAluno
     */
    Aluno_VO alunoVO;
    Aluno_RN alunoRN;

    public FAluno() {
        initComponents();
    }

    public FAluno(Aluno_VO vo) {
        initComponents();
        try {
            alunoVO = vo;
            alunoRN = new Aluno_RN();

            this.jTXFCPFNew.setText(alunoVO.getCpf());
            this.jTXFGrrNew.setText(alunoVO.getPk_grr());
            this.jTXFNomeNew.setText(alunoVO.getNome());
            this.jPASSenhaNew.setText(alunoVO.getSenha());
        } catch (Exception ex) {
            Logger.getLogger(FAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTXFGrrNew = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTXFNomeNew = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTXFCPFNew = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPASSenhaNew = new javax.swing.JPasswordField();
        jBTNCadastrar = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTXFGrr = new javax.swing.JTextField();
        jTXFNome = new javax.swing.JTextField();
        jTXFCPF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBTNEditar = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jPASSenha = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jTXFNewGrr = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTXFGrrbusca = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTXABusca = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTXFGrrDel = new javax.swing.JTextField();
        jBDel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTXAExcluido = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aluno");

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(300, 311));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(344, 320));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("GRR:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));
        jPanel2.add(jTXFGrrNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 321, -1));

        jLabel16.setText("Nome:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, -1, -1));
        jPanel2.add(jTXFNomeNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 71, 321, -1));

        jLabel18.setText("CPF:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        jPanel2.add(jTXFCPFNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 321, -1));

        jLabel21.setText("Senha:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        jPanel2.add(jPASSenhaNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 320, -1));

        jBTNCadastrar.setText("Cadastrar");
        jBTNCadastrar.setToolTipText("Alterar Cadastro");
        jBTNCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTNCadastrarActionPerformed(evt);
            }
        });
        jPanel2.add(jBTNCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 100, -1));

        jTabbedPane1.addTab("Novo Cadastro", jPanel2);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("CPF:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel1.setText("GRR:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jTXFGrr.setEditable(false);
        jTXFGrr.setBackground(new java.awt.Color(255, 255, 255));
        jTXFGrr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTXFGrrActionPerformed(evt);
            }
        });
        jPanel1.add(jTXFGrr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 321, -1));
        jPanel1.add(jTXFNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 321, -1));
        jPanel1.add(jTXFCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 321, -1));

        jLabel2.setText("Nome:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jBTNEditar.setText("Alterar Cadastro");
        jBTNEditar.setToolTipText("Alterar Cadastro");
        jBTNEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTNEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jBTNEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jLabel7.setText("Senha:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));
        jPanel1.add(jPASSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 320, -1));

        jLabel4.setText("Novo GRR: (repitir se inalterado)");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jTXFNewGrr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTXFNewGrrActionPerformed(evt);
            }
        });
        jPanel1.add(jTXFNewGrr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 320, -1));

        jTabbedPane1.addTab("Alterar", jPanel1);

        jLabel5.setText("GRR:");

        jTXFGrrbusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTXFGrrbuscaActionPerformed(evt);
            }
        });

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jTXABusca.setColumns(20);
        jTXABusca.setRows(5);
        jScrollPane1.setViewportView(jTXABusca);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTXFGrrbusca)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 98, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTXFGrrbusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Buscar", jPanel3);

        jLabel6.setText("GRR:");

        jTXFGrrDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTXFGrrDelActionPerformed(evt);
            }
        });

        jBDel.setText("Deletar");
        jBDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDelActionPerformed(evt);
            }
        });

        jTXAExcluido.setColumns(20);
        jTXAExcluido.setRows(5);
        jScrollPane2.setViewportView(jTXAExcluido);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTXFGrrDel)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jBDel)
                        .addGap(0, 116, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTXFGrrDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBDel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Deletar", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Visualizar");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTXFNewGrrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTXFNewGrrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTXFNewGrrActionPerformed

    private void jBTNEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTNEditarActionPerformed
        try {
            alunoVO.setPk_grr(this.jTXFGrr.getText());
            alunoVO.setNewPKGrr(this.jTXFNewGrr.getText());
            alunoVO.setCpf(this.jTXFCPF.getText());
            alunoVO.setNome(this.jTXFNome.getText());
            alunoVO.setSenha(new String(this.jPASSenha.getPassword()).trim());

            if(alunoRN.editarAluno(alunoVO))
                this.jTXFCPFNew.setText(alunoVO.getCpf());
                this.jTXFGrrNew.setText(alunoVO.getPk_grr());
                this.jTXFNomeNew.setText(alunoVO.getNome());
                this.jPASSenhaNew.setText(alunoVO.getSenha());
                this.jTXFGrrbusca.setText(alunoVO.getPk_grr());
                this.jTXFGrrDel.setText(alunoVO.getPk_grr());
                JOptionPane.showMessageDialog(null,"Aluno Alterado");

        } catch (ParseException ex) {
            Logger.getLogger(FAluno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(FAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBTNEditarActionPerformed

    private void jTXFGrrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTXFGrrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTXFGrrActionPerformed

    private void jBTNCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTNCadastrarActionPerformed
        try {
            alunoVO.setPk_grr(this.jTXFGrrNew.getText());
            alunoVO.setCpf(this.jTXFCPFNew.getText());
            alunoVO.setNome(this.jTXFNomeNew.getText());
            alunoVO.setSenha(new String(this.jPASSenhaNew.getPassword()).trim());

            //se sucesso, recarregar aba alterações
            if (alunoRN.inserirAluno(alunoVO)) {
                this.jTXFCPF.setText(alunoVO.getCpf());
                this.jTXFGrr.setText(alunoVO.getPk_grr());
                this.jTXFNome.setText(alunoVO.getNome());
                this.jPASSenha.setText(alunoVO.getSenha());
                this.jTXFGrrbusca.setText(alunoVO.getPk_grr());
                this.jTXFGrrDel.setText(alunoVO.getPk_grr());
                JOptionPane.showMessageDialog(null,"Aluno Inserido");
            }

        } catch (ParseException ex) {
            Logger.getLogger(FAluno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(FAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBTNCadastrarActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        try {
            alunoVO.setPk_grr(this.jTXFGrrbusca.getText());

            if(alunoRN.selectAluno(alunoVO))
            jTXABusca.setText("GRR: " + alunoVO.getPk_grr() +
                                   "\nNome: " + alunoVO.getNome()+
                                   "\nCPF: " + alunoVO.getCpf() + 
                                   "\nSenha: " + alunoVO.getSenha());
            this.jTXFCPF.setText(alunoVO.getCpf());
            this.jTXFGrr.setText(alunoVO.getPk_grr());
            this.jTXFNome.setText(alunoVO.getNome());
            this.jPASSenha.setText(alunoVO.getSenha());
            this.jTXFCPFNew.setText(alunoVO.getCpf());
            this.jTXFGrrNew.setText(alunoVO.getPk_grr());
            this.jTXFNomeNew.setText(alunoVO.getNome());
            this.jPASSenhaNew.setText(alunoVO.getSenha());
            this.jTXFGrrDel.setText(alunoVO.getPk_grr());

        } catch (Exception ex) {
            Logger.getLogger(FAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jTXFGrrbuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTXFGrrbuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTXFGrrbuscaActionPerformed

    private void jBDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDelActionPerformed
        try {
            alunoVO.setPk_grr(this.jTXFGrrDel.getText());

            if(alunoRN.excluirAluno(alunoVO))
            jTXAExcluido.setText("O seguinte aluno foi excluido:\nGRR: " + alunoVO.getPk_grr() +
                                   "\nNome: " + alunoVO.getNome()+
                                   "\nCPF: " + alunoVO.getCpf() + 
                                   "\nSenha: " + alunoVO.getSenha());
            this.jTXFCPF.setText(alunoVO.getCpf());
            this.jTXFGrr.setText(alunoVO.getPk_grr());
            this.jTXFNome.setText(alunoVO.getNome());
            this.jPASSenha.setText(alunoVO.getSenha());
            this.jTXFCPFNew.setText(alunoVO.getCpf());
            this.jTXFGrrNew.setText(alunoVO.getPk_grr());
            this.jTXFNomeNew.setText(alunoVO.getNome());
            this.jPASSenhaNew.setText(alunoVO.getSenha());

        } catch (Exception ex) {
            Logger.getLogger(FAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBDelActionPerformed

    private void jTXFGrrDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTXFGrrDelActionPerformed
        
    }//GEN-LAST:event_jTXFGrrDelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBDel;
    private javax.swing.JToggleButton jBTNCadastrar;
    private javax.swing.JToggleButton jBTNEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPASSenha;
    private javax.swing.JPasswordField jPASSenhaNew;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTXABusca;
    private javax.swing.JTextArea jTXAExcluido;
    private javax.swing.JTextField jTXFCPF;
    private javax.swing.JTextField jTXFCPFNew;
    private javax.swing.JTextField jTXFGrr;
    private javax.swing.JTextField jTXFGrrDel;
    private javax.swing.JTextField jTXFGrrNew;
    private javax.swing.JTextField jTXFGrrbusca;
    private javax.swing.JTextField jTXFNewGrr;
    private javax.swing.JTextField jTXFNome;
    private javax.swing.JTextField jTXFNomeNew;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
