/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetobd;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import projetobd.Model.Turma_RN;
import projetobd.Model.Turma_VO;

/**
 *
 * @author uliss
 */
public class FTurma extends javax.swing.JFrame {

    Turma_RN turmaRN;
    Turma_VO turmaVO;
    /**
     * Creates new form FTurma
     */
    public FTurma() {
        turmaRN = new Turma_RN();
        turmaVO = new Turma_VO();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTFId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTFKCurso = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTFFkIdDisciplina = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTFNumCurso = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTFSemestre = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTFFkIdProfessor = new javax.swing.JTextField();
        jBInserir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFIdEditar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFNewIDEditar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFKCursoEdit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFFkIdDisciplinaEdit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFNumCursoEdit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFSemestreEdit = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTFFkIdProfessorEdit = new javax.swing.JTextField();
        jBEditar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTFIdBuscar = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTABuscar = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTFIdExcluir = new javax.swing.JTextField();
        jBExcluir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAExcluir = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Turma");

        jLabel8.setText("ID ");

        jLabel10.setText("ID do curso");

        jLabel11.setText("ID da Disciplina");

        jLabel12.setText("Numero do curso");

        jLabel13.setText("Semestre");

        jLabel14.setText("ID do professor");

        jBInserir.setText("Inserir");
        jBInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInserirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTFId)
                    .addComponent(jTFFkIdProfessor))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jTFSemestre)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jTFNumCurso)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jTFFkIdDisciplina)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jTFKCurso)
                .addGap(10, 10, 10))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jPanel1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jBInserir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFKCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFFkIdDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNumCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFFkIdProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBInserir)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inserir", jPanel1);

        jLabel1.setText("ID ");

        jLabel2.setText("New ID");

        jLabel3.setText("ID do curso");

        jLabel4.setText("ID da Disciplina");

        jLabel5.setText("Numero do curso");

        jLabel6.setText("Semestre");

        jLabel7.setText("ID do professor");

        jBEditar.setText("Editar");
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jBEditar)
                    .addComponent(jTFFkIdProfessorEdit)
                    .addComponent(jTFSemestreEdit)
                    .addComponent(jTFNumCursoEdit)
                    .addComponent(jTFFkIdDisciplinaEdit)
                    .addComponent(jTFKCursoEdit)
                    .addComponent(jTFNewIDEditar)
                    .addComponent(jTFIdEditar))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(351, 351, 351))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFIdEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNewIDEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFKCursoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFFkIdDisciplinaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNumCursoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFSemestreEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFFkIdProfessorEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBEditar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Editar", jPanel2);

        jLabel9.setText("ID ");

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jTABuscar.setColumns(20);
        jTABuscar.setRows(5);
        jScrollPane1.setViewportView(jTABuscar);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jBBuscar)
                            .addComponent(jTFIdBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFIdBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBBuscar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Buscar", jPanel3);

        jLabel15.setText("ID ");

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jTAExcluir.setColumns(20);
        jTAExcluir.setRows(5);
        jScrollPane2.setViewportView(jTAExcluir);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jBExcluir)
                            .addComponent(jTFIdExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFIdExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBExcluir)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Excluir", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInserirActionPerformed
        try {
            turmaVO.setPKIDturma(jTFId.getText());
            turmaVO.setFKCurso(jTFKCurso.getText());
            turmaVO.setFKIDdisciplina(jTFFkIdDisciplina.getText());
            turmaVO.setNum_curso(jTFNumCurso.getText());
            turmaVO.setSemestre(jTFSemestre.getText());
            turmaVO.setFKIDprofessor(jTFFkIdProfessor.getText());
            
            if (turmaRN.inserirTurma(turmaVO)) {
                jTFIdEditar.setText(turmaVO.getPKIDturma());
                jTFKCursoEdit.setText(turmaVO.getFKCurso());
                jTFFkIdDisciplinaEdit.setText(turmaVO.getFKIDdisciplina());
                jTFNumCursoEdit.setText(turmaVO.getNum_curso());
                jTFSemestreEdit.setText(turmaVO.getSemestre());
                jTFFkIdProfessorEdit.setText(turmaVO.getFKIDprofessor());
                jTFIdBuscar.setText(turmaVO.getPKIDturma());
                jTFIdExcluir.setText(turmaVO.getPKIDturma());
                JOptionPane.showMessageDialog(null, "Turma Inserida");
            }
            
        }  catch (ParseException ex) {
            Logger.getLogger(FTurma.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e) {
            Logger.getLogger(FTurma.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jBInserirActionPerformed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        try {
            turmaVO.setPKIDturma(jTFIdEditar.getText());
            turmaVO.setNewPkIDTurma(jTFNewIDEditar.getText());
            turmaVO.setFKCurso(jTFKCursoEdit.getText());
            turmaVO.setFKIDdisciplina(jTFFkIdDisciplinaEdit.getText());
            turmaVO.setNum_curso(jTFNumCursoEdit.getText());
            turmaVO.setSemestre(jTFSemestreEdit.getText());
            turmaVO.setFKIDprofessor(jTFFkIdProfessorEdit.getText());
            
            if (turmaRN.editarTurma(turmaVO)) {
                jTFId.setText(turmaVO.getPKIDturma());
                jTFKCurso.setText(turmaVO.getFKCurso());
                jTFFkIdDisciplina.setText(turmaVO.getFKIDdisciplina());
                jTFNumCurso.setText(turmaVO.getNum_curso());
                jTFSemestre.setText(turmaVO.getSemestre());
                jTFFkIdProfessor.setText(turmaVO.getFKIDprofessor());
                jTFIdBuscar.setText(turmaVO.getPKIDturma());
                jTFIdExcluir.setText(turmaVO.getPKIDturma());
                JOptionPane.showMessageDialog(null, "Turma Editada");
            }
            
        }  catch (ParseException ex) {
            Logger.getLogger(FTurma.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e) {
            Logger.getLogger(FTurma.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        try {
            turmaVO.setPKIDturma(jTFIdBuscar.getText());
            
            if (turmaRN.buscarTurma(turmaVO)) {
                
                jTABuscar.setText("ID: " + turmaVO.getPKIDturma()
                + "\nID do Curso: " + turmaVO.getFKCurso()
                + "\nID da disciplina: " + turmaVO.getFKIDdisciplina()
                + "\nNumero do curso: " + turmaVO.getNum_curso()
                + "\nSemestre: " + turmaVO.getSemestre()
                + "\nID do professor: " + turmaVO.getFKIDprofessor());
                
                
                jTFIdEditar.setText(turmaVO.getPKIDturma());
                jTFKCursoEdit.setText(turmaVO.getFKCurso());
                jTFFkIdDisciplinaEdit.setText(turmaVO.getFKIDdisciplina());
                jTFNumCursoEdit.setText(turmaVO.getNum_curso());
                jTFSemestreEdit.setText(turmaVO.getSemestre());
                jTFFkIdProfessorEdit.setText(turmaVO.getFKIDprofessor());
                jTFId.setText(turmaVO.getPKIDturma());
                jTFKCurso.setText(turmaVO.getFKCurso());
                jTFFkIdDisciplina.setText(turmaVO.getFKIDdisciplina());
                jTFNumCurso.setText(turmaVO.getNum_curso());
                jTFSemestre.setText(turmaVO.getSemestre());
                jTFFkIdProfessor.setText(turmaVO.getFKIDprofessor());
                jTFIdExcluir.setText(turmaVO.getPKIDturma());
            }
            
        }  catch (ParseException ex) {
            Logger.getLogger(FTurma.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e) {
            Logger.getLogger(FTurma.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        try {
            turmaVO.setPKIDturma(jTFIdExcluir.getText());
            
            if (turmaRN.excluirTurma(turmaVO)) {
                
                jTAExcluir.setText("Turma Excluida: \nID: " + turmaVO.getPKIDturma()
                + "\nID do Curso: " + turmaVO.getFKCurso()
                + "\nID da disciplina: " + turmaVO.getFKIDdisciplina()
                + "\nNumero do curso: " + turmaVO.getNum_curso()
                + "\nSemestre: " + turmaVO.getSemestre()
                + "\nID do professor: " + turmaVO.getFKIDprofessor());
                
                
                jTFIdEditar.setText(turmaVO.getPKIDturma());
                jTFKCursoEdit.setText(turmaVO.getFKCurso());
                jTFFkIdDisciplinaEdit.setText(turmaVO.getFKIDdisciplina());
                jTFNumCursoEdit.setText(turmaVO.getNum_curso());
                jTFSemestreEdit.setText(turmaVO.getSemestre());
                jTFFkIdProfessorEdit.setText(turmaVO.getFKIDprofessor());
                jTFId.setText(turmaVO.getPKIDturma());
                jTFKCurso.setText(turmaVO.getFKCurso());
                jTFFkIdDisciplina.setText(turmaVO.getFKIDdisciplina());
                jTFNumCurso.setText(turmaVO.getNum_curso());
                jTFSemestre.setText(turmaVO.getSemestre());
                jTFFkIdProfessor.setText(turmaVO.getFKIDprofessor());
                jTFIdBuscar.setText(turmaVO.getPKIDturma());
            }
            
        }  catch (ParseException ex) {
            Logger.getLogger(FTurma.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e) {
            Logger.getLogger(FTurma.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jBExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FTurma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBInserir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTABuscar;
    private javax.swing.JTextArea jTAExcluir;
    private javax.swing.JTextField jTFFkIdDisciplina;
    private javax.swing.JTextField jTFFkIdDisciplinaEdit;
    private javax.swing.JTextField jTFFkIdProfessor;
    private javax.swing.JTextField jTFFkIdProfessorEdit;
    private javax.swing.JTextField jTFId;
    private javax.swing.JTextField jTFIdBuscar;
    private javax.swing.JTextField jTFIdEditar;
    private javax.swing.JTextField jTFIdExcluir;
    private javax.swing.JTextField jTFKCurso;
    private javax.swing.JTextField jTFKCursoEdit;
    private javax.swing.JTextField jTFNewIDEditar;
    private javax.swing.JTextField jTFNumCurso;
    private javax.swing.JTextField jTFNumCursoEdit;
    private javax.swing.JTextField jTFSemestre;
    private javax.swing.JTextField jTFSemestreEdit;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
